name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: download
      uses: wei/wget@v1
      with:
        args: -O cmake-3.15.1-Linux-x86_64.sh https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1-Linux-x86_64.sh
    - name: setup
      run: |
        chmod +x cmake-3.15.1-Linux-x86_64.sh
        ./cmake-3.15.1-Linux-x86_64.sh --skip-license --prefix=${HOME}/cmake
      working-directory: ${HOME}/cache/
    - name: setup
      run: ${HOME}/cmake/bin/cmake -S . -B./build
    - name: build
      run: ${HOME}/cmake/bin/cmake --build ./build -j2
    - name: test
      run: ${HOME}/cmake/bin/ctest -V
      working-directory: ./build
