name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: setup
      run: |
        wget https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1-Linux-x86_64.sh
        chmod +x cmake-3.15.1-Linux-x86_64.sh
        ./cmake-3.15.1-Linux-x86_64.sh --skip-license --prefix=~/cmake
      
    - name: setup
      run: |
        ~/cmake/bin/cmake -S . -B~/build
    - name: build
      run: ~/cmake/bin/cmake --build ~/build -j2
    - name: test
      run: ~/cmake/bin/ctest -V
      working-directory: ~/build

