name: C/C++ CI

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: dl
      working-directory: ./temp
      run: wget https://github.com/Kitware/CMake/releases/download/v3.15.1/cmake-3.15.1-Linux-x86_64.sh
    - name: exec
      working-directory: ./temp
      run: chmod +x ./cmake-3.15.1-Linux-x86_64.sh
    - name: install_cmake
      working-directory: ./temp
      run: ./cmake-3.15.1-Linux-x86_64.sh --skip-license --prefix=${HOME}/cmake
    - name: setup
      run: ${HOME}/cmake/bin/cmake -S . -B./build
    - name: build
      run: ${HOME}/cmake/bin/cmake --build ./build -j2
    - name: test
      run: ${HOME}/cmake/bin/ctest -V
      working-directory: ./build
