name: CI

on: [push, pull_request]

jobs:
  build:
    strategy:
        matrix:
          cc: [ gcc ]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: install_cmake
      run: | 
        wget https://github.com/Kitware/CMake/releases/download/v3.15.5/cmake-3.15.5-Linux-x86_64.sh  -O ${HOME}/cmake-3.15.5-Linux-x86_64.sh
        chmod +x ${HOME}/cmake-3.15.5-Linux-x86_64.sh
        ${HOME}/cmake-3.15.5-Linux-x86_64.sh --skip-license --prefix=${HOME}
    - name: configure
      run: ${HOME}/bin/cmake -S . -B./build -DCMAKE_BUILD_TYPE=Release
    - name: build
      run: ${HOME}/bin/cmake --build ./build -j2
    - name: test
      run: ${HOME}/bin/ctest -V
      working-directory: ./build
